// priority: 50
StartupEvents.registry('sound_event', event => {
    event.create("mrqx_disc_pack:abyssgazer_song")
    event.create("mrqx_disc_pack:arghena_song")
    event.create("mrqx_disc_pack:dantalion_song")
    event.create("mrqx_disc_pack:desive_song")
    event.create("mrqx_disc_pack:designant_song")
    event.create("mrqx_disc_pack:rain_of_conflict_in_a_radiant_abyss_song")
    event.create("mrqx_disc_pack:inverted_world_song")
    event.create("mrqx_disc_pack:straight_into_the_lights_song")
    event.create("mrqx_disc_pack:kirakira_noel_story_song")
    event.create("mrqx_disc_pack:fudahuang_song")
    event.create("mrqx_disc_pack:legend_of_bloodywolf")
})

StartupEvents.registry('item', event => {
    event.create("mrqx_disc_pack:abyssgazer_disc", "music_disc")
        .song("mrqx_disc_pack:abyssgazer_song", 165)
        .analogOutput(1)
        .texture("mrqx_disc_pack:item/abyssgazer_song_disc")
        .maxStackSize(1)
        .tag('minecraft:music_discs')

    event.create("mrqx_disc_pack:arghena_disc", "music_disc")
        .song("mrqx_disc_pack:arghena_song", 156)
        .analogOutput(1)
        .texture("mrqx_disc_pack:item/arghena_song_disc")
        .maxStackSize(1)
        .tag('minecraft:music_discs')

    event.create("mrqx_disc_pack:dantalion_disc", "music_disc")
        .song("mrqx_disc_pack:dantalion_song", 249)
        .analogOutput(1)
        .texture("mrqx_disc_pack:item/dantalion_song_disc")
        .maxStackSize(1)
        .tag('minecraft:music_discs')

    event.create("mrqx_disc_pack:desive_disc", "music_disc")
        .song("mrqx_disc_pack:desive_song", 170)
        .analogOutput(1)
        .texture("mrqx_disc_pack:item/desive_song_disc")
        .maxStackSize(1)
        .tag('minecraft:music_discs')

    event.create("mrqx_disc_pack:designant_disc", "music_disc")
        .song("mrqx_disc_pack:designant_song", 181)
        .analogOutput(1)
        .texture("mrqx_disc_pack:item/designant_song_disc")
        .maxStackSize(1)
        .tag('minecraft:music_discs')

    event.create("mrqx_disc_pack:rain_of_conflict_in_a_radiant_abyss_disc", "music_disc")
        .song("mrqx_disc_pack:rain_of_conflict_in_a_radiant_abyss_song", 151)
        .analogOutput(1)
        .texture("mrqx_disc_pack:item/rain_of_conflict_in_a_radiant_abyss_song_disc")
        .maxStackSize(1)
        .tag('minecraft:music_discs')

    event.create("mrqx_disc_pack:inverted_world_disc", "music_disc")
        .song("mrqx_disc_pack:inverted_world_song", 132)
        .analogOutput(1)
        .texture("mrqx_disc_pack:item/inverted_world_song_disc")
        .maxStackSize(1)
        .tag('minecraft:music_discs')

    event.create("mrqx_disc_pack:straight_into_the_lights_disc", "music_disc")
        .song("mrqx_disc_pack:straight_into_the_lights_song", 154)
        .analogOutput(1)
        .texture("mrqx_disc_pack:item/straight_into_the_lights_song_disc")
        .maxStackSize(1)
        .tag('minecraft:music_discs')

    event.create("mrqx_disc_pack:kirakira_noel_story_disc", "music_disc")
        .song("mrqx_disc_pack:kirakira_noel_story_song", 137)
        .analogOutput(1)
        .texture("mrqx_disc_pack:item/kirakira_noel_story_song_disc")
        .maxStackSize(1)
        .tag('minecraft:music_discs')

    event.create("mrqx_disc_pack:fudahuang_disc", "music_disc")
        .song("mrqx_disc_pack:fudahuang_song", 219)
        .analogOutput(1)
        .texture("mrqx_disc_pack:item/fudahuang_song_disc")
        .maxStackSize(1)
        .tag('minecraft:music_discs')

    event.create("mrqx_disc_pack:legend_of_bloodywolf_disc", "music_disc")
        .song("mrqx_disc_pack:legend_of_bloodywolf", 154)
        .analogOutput(1)
        .texture("mrqx_disc_pack:item/legend_of_bloodywolf")
        .maxStackSize(1)
        .tag('minecraft:music_discs')
})