// priority: 950
const $mrqxArrayList = Java.loadClass('java.util.ArrayList')
const $mrqxSculkTaintEffect = Java.loadClass('se.mickelus.tetra.effect.SculkTaintEffect')
const $mrqxTamableAnimal = Java.loadClass('net.minecraft.world.entity.TamableAnimal')
const $mrqxDamageType = Java.loadClass('net.mehvahdjukaar.dummmmmmy.common.DamageType')
const $mrqxDeployerFakePlayer = Java.loadClass('com.simibubi.create.content.kinetics.deployer.DeployerFakePlayer')
const $mrqxCombatRules = Java.loadClass('net.minecraft.world.damagesource.CombatRules')
const $mrqxInventory = Java.loadClass('net.minecraft.world.entity.player.Inventory')
const $mrqxEnchantmentHelper = Java.loadClass('net.minecraft.world.item.enchantment.EnchantmentHelper')
const $mrqxChainBlock = Java.loadClass('twilightforest.entity.ChainBlock')
const $mrqxTFEntities = Java.loadClass('twilightforest.init.TFEntities')
const $mrqxSerializer = Java.loadClass('net.minecraft.network.chat.Component$Serializer')
const $mrqxFTBChunksAPI = Java.loadClass('dev.ftb.mods.ftbchunks.data.FTBChunksAPI')
const $mrqxChunkDimPos = Java.loadClass('dev.ftb.mods.ftblibrary.math.ChunkDimPos')