// priority: 1000
const tagWorth = {
    '#kubejs:organ': 1,
    '#kubejs:stomach': 10,
    '#kubejs:eat_effect': 30,
    '#kubejs:infinity': 300,
    '#kubejs:damage_only': 100,
    '#kubejs:active_only': 100,
    '#kubejs:loot_entity_only': 500,
    '#kubejs:muscle': 10,
    '#kubejs:rose': 50,
    '#kubejs:active': 50,
    '#kubejs:heart': 50,
    '#kubejs:liver': 10,
    '#kubejs:kidney': 40,
    '#kubejs:machine': 30,
    '#kubejs:revolution': 50,
    '#kubejs:rclick_only': 80,
    '#kubejs:player_tick_only': 100,
    '#kubejs:lung': 40,
    '#kubejs:resource': 100,
    '#kubejs:key_pressed': 100,
    '#kubejs:spleen': 40,
    '#kubejs:player_tick': 30,
    '#kubejs:eat_effect_only': 60,
    '#kubejs:candy': 100,
    '#kubejs:pancreas': 30,
    '#kubejs:magic': 80,
    '#kubejs:overmagic_only': 100,
    '#kubejs:spine': 50,
    '#kubejs:bear': 90,
    '#kubejs:break_only': 70,
    '#kubejs:break': 50,
    '#kubejs:appendix': 100,
    '#kubejs:legends': 800,
    '#kubejs:evolution': 50,
    '#kubejs:bear_only': 150,
    '#kubejs:loot_chest_only': 500,
    '#kubejs:enchant_only': 400,
    '#kubejs:warp': 300,
    '#kubejs:organ_count_only': 70,
    '#kubejs:relics': 5,
    '#kubejs:rib': 20,
    '#kubejs:intestine': 15,
    '#kubejs:on_fire_check': 50,
    '#kubejs:auto_active': 100,
    '#kubejs:exclued_lucky_block': 77,
    '#kubejs:food': 30,
    '#kubejs:infected': -10,
    '#kubejs:fantasy': 5,
    '#kubejs:huge': 50,
    '#kubejs:prehistory': 100,
    '#kubejs:dragon': 500,
}

function registerTagWorth(tag, worth) {
    tagWorth[tag] = worth
}